### ISSUE TITLE
实盘trdPlaceOrder 发委托抛异常

### ISSUE THREAD

**Issue by rayallenwu** [llmyfa/java-for-FutuOpenD#3]
com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:99)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:515)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:478)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:596)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:281)
	at com.google.protobuf.CodedInputStream.readGroup(CodedInputStream.java:424)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:505)
	at com.google.protobuf.GeneratedMessage.parseUnknownField(GeneratedMessage.java:205)
	at com.futu.opend.api.protobuf.TrdUpdateOrder$Response.<init>(TrdUpdateOrder.java:963)
	at com.futu.opend.api.protobuf.TrdUpdateOrder$Response.<init>(TrdUpdateOrder.java:946)
	at com.futu.opend.api.protobuf.TrdUpdateOrder$Response$1.parsePartialFrom(TrdUpdateOrder.java:1028)
	at com.futu.opend.api.protobuf.TrdUpdateOrder$Response$1.parsePartialFrom(TrdUpdateOrder.java:1)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:137)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:169)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.futu.opend.api.protobuf.TrdUpdateOrder$Response.parseFrom(TrdUpdateOrder.java:1230)
	at com.futu.opend.api.impl.TrdPlaceOrderExec.parse(TrdPlaceOrderExec.java:104)
	at com.futu.opend.api.impl.TrdPlaceOrderExec.parse(TrdPlaceOrderExec.java:1)
	at com.futu.opend.api.impl.Client$2.run(Client.java:193)

但这个异常，在模拟环境不存在。一切换到trdUnlockTradeForReal，再发送委托，就会抛上面的exception

**Comment by rayallenwu** [comment]
<push_proto_type>0</push_proto_type> XML里设置成0，问题就不会出现。
close the issue.
